-- Standard-SQL reference. Execute an engine-specific script instead.
-- Professional POS schema v1. Amounts use exact decimals; FX is base units per 1 foreign unit.

CREATE TABLE schema_version (
    version_no INTEGER PRIMARY KEY,
    checksum VARCHAR(64) NOT NULL,
    installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(4000) NOT NULL
);

CREATE TABLE business_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(200) NOT NULL,
    legal_name VARCHAR(200),
    address VARCHAR(1000),
    phone VARCHAR(80),
    email VARCHAR(200),
    tax_number VARCHAR(100),
    country VARCHAR(100),
    time_zone VARCHAR(80) NOT NULL,
    footer VARCHAR(1000),
    logo_path VARCHAR(1000)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE permissions (
    permission_code VARCHAR(60) PRIMARY KEY
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_code VARCHAR(60) NOT NULL,
    PRIMARY KEY(role_id,permission_code),
    CONSTRAINT fk_role_permissions_role_id FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_role_permissions_permission_code FOREIGN KEY (permission_code) REFERENCES permissions(permission_code)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    full_name VARCHAR(200) NOT NULL,
    password_hash VARCHAR(512) NOT NULL,
    role_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    last_login TIMESTAMP,
    must_change BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE currencies (
    code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    decimal_places INTEGER NOT NULL CHECK(decimal_places BETWEEN 0 AND 6),
    symbol_before BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(10) NOT NULL,
    effective_date DATE NOT NULL,
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(currency_code,effective_date),
    CONSTRAINT fk_exchange_rates_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code),
    CONSTRAINT fk_exchange_rates_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE tax_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    rate DECIMAL(28,12) NOT NULL CHECK(rate>=0 AND rate<=100),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    name_ar VARCHAR(100),
    tax_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_categories_tax_id FOREIGN KEY (tax_id) REFERENCES tax_rates(id)
);

CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    name_ar VARCHAR(80),
    fractional BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(12) NOT NULL CHECK(kind IN ('CUSTOMER','SUPPLIER')),
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    company VARCHAR(200),
    contact VARCHAR(200),
    phone VARCHAR(80),
    email VARCHAR(200),
    address VARCHAR(1000),
    tax_number VARCHAR(100),
    currency_code VARCHAR(10) NOT NULL,
    credit_limit DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(credit_limit>=0),
    terms_days INTEGER NOT NULL DEFAULT 0 CHECK(terms_days>=0),
    discount_pct DECIMAL(28,12) NOT NULL DEFAULT 0 CHECK(discount_pct BETWEEN 0 AND 100),
    notes VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_parties_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    name_ar VARCHAR(200),
    description VARCHAR(2000),
    brand VARCHAR(100),
    category_id BIGINT,
    unit_id BIGINT NOT NULL,
    tax_id BIGINT NOT NULL,
    preferred_supplier_id BIGINT,
    parent_product_id BIGINT,
    variant_label VARCHAR(200),
    price DECIMAL(24,6) NOT NULL CHECK(price>=0),
    wholesale_price DECIMAL(24,6),
    current_cost DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(current_cost>=0),
    last_cost DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(last_cost>=0),
    on_hand DECIMAL(24,6) NOT NULL DEFAULT 0,
    stock_value DECIMAL(24,6) NOT NULL DEFAULT 0,
    min_stock DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(min_stock>=0),
    reorder_level DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(reorder_level>=0),
    max_stock DECIMAL(24,6),
    track_stock BOOLEAN NOT NULL DEFAULT TRUE,
    allow_negative BOOLEAN NOT NULL DEFAULT FALSE,
    fractional BOOLEAN NOT NULL DEFAULT FALSE,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_products_category_id FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_products_unit_id FOREIGN KEY (unit_id) REFERENCES units(id),
    CONSTRAINT fk_products_tax_id FOREIGN KEY (tax_id) REFERENCES tax_rates(id),
    CONSTRAINT fk_products_preferred_supplier_id FOREIGN KEY (preferred_supplier_id) REFERENCES parties(id),
    CONSTRAINT fk_products_parent_product_id FOREIGN KEY (parent_product_id) REFERENCES products(id)
);

CREATE TABLE product_barcodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    barcode VARCHAR(100) NOT NULL UNIQUE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_product_barcodes_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    old_price DECIMAL(24,6) NOT NULL,
    new_price DECIMAL(24,6) NOT NULL,
    old_cost DECIMAL(24,6) NOT NULL,
    new_cost DECIMAL(24,6) NOT NULL,
    user_id BIGINT NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_price_history_product_id FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_price_history_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    name_ar VARCHAR(150),
    account_type VARCHAR(12) NOT NULL CHECK(account_type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')),
    parent_id BIGINT,
    system_account BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_accounts_parent_id FOREIGN KEY (parent_id) REFERENCES accounts(id)
);

CREATE TABLE payment_methods (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    account_code VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    is_cash BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_payment_methods_account_code FOREIGN KEY (account_code) REFERENCES accounts(code)
);

CREATE TABLE document_sequences (
    sequence_code VARCHAR(30) PRIMARY KEY,
    next_value BIGINT NOT NULL CHECK(next_value>0)
);

CREATE TABLE cash_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    opening_cash DECIMAL(24,6) NOT NULL CHECK(opening_cash>=0),
    expected_cash DECIMAL(24,6),
    counted_cash DECIMAL(24,6),
    difference DECIMAL(24,6),
    notes VARCHAR(2000),
    CONSTRAINT fk_cash_sessions_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    supplier_id BIGINT NOT NULL,
    ordered_on DATE NOT NULL,
    expected_on DATE,
    currency_code VARCHAR(10) NOT NULL,
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    status VARCHAR(25) NOT NULL CHECK(status IN ('DRAFT','SENT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
    notes VARCHAR(2000),
    created_by BIGINT NOT NULL,
    CONSTRAINT fk_purchase_orders_supplier_id FOREIGN KEY (supplier_id) REFERENCES parties(id),
    CONSTRAINT fk_purchase_orders_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code),
    CONSTRAINT fk_purchase_orders_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE po_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    received_qty DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(received_qty>=0 AND received_qty<=quantity),
    unit_cost DECIMAL(24,6) NOT NULL CHECK(unit_cost>=0),
    discount_pct DECIMAL(28,12) NOT NULL DEFAULT 0 CHECK(discount_pct BETWEEN 0 AND 100),
    tax_rate DECIMAL(28,12) NOT NULL DEFAULT 0 CHECK(tax_rate BETWEEN 0 AND 100),
    CONSTRAINT fk_po_lines_order_id FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_po_lines_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(30) NOT NULL CHECK(kind IN ('SALE','PURCHASE','SALE_RETURN','PURCHASE_RETURN','CUSTOMER_PAYMENT','SUPPLIER_PAYMENT','EXPENSE','CASH_IN','CASH_OUT','OPENING','ADJUSTMENT','MANUAL','REVERSAL')),
    number VARCHAR(40) NOT NULL UNIQUE,
    request_key VARCHAR(80) NOT NULL UNIQUE,
    original_id BIGINT,
    exchange_id VARCHAR(80),
    order_id BIGINT,
    party_id BIGINT,
    party_name VARCHAR(200),
    party_address VARCHAR(1000),
    party_tax_number VARCHAR(100),
    document_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date DATE,
    currency_code VARCHAR(10) NOT NULL,
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    subtotal DECIMAL(24,6) NOT NULL DEFAULT 0,
    discount DECIMAL(24,6) NOT NULL DEFAULT 0,
    net DECIMAL(24,6) NOT NULL DEFAULT 0,
    tax DECIMAL(24,6) NOT NULL DEFAULT 0,
    total DECIMAL(24,6) NOT NULL DEFAULT 0,
    base_net DECIMAL(24,6) NOT NULL DEFAULT 0,
    base_tax DECIMAL(24,6) NOT NULL DEFAULT 0,
    base_total DECIMAL(24,6) NOT NULL DEFAULT 0,
    cogs DECIMAL(24,6) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    reference VARCHAR(200),
    notes VARCHAR(2000),
    reason VARCHAR(1000),
    store_name VARCHAR(200),
    store_address VARCHAR(1000),
    store_phone VARCHAR(80),
    store_tax_number VARCHAR(100),
    logo_path VARCHAR(1000),
    footer VARCHAR(1000),
    created_by BIGINT NOT NULL,
    approved_by BIGINT,
    cash_session_id BIGINT,
    CONSTRAINT fk_documents_original_id FOREIGN KEY (original_id) REFERENCES documents(id),
    CONSTRAINT fk_documents_order_id FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_documents_party_id FOREIGN KEY (party_id) REFERENCES parties(id),
    CONSTRAINT fk_documents_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code),
    CONSTRAINT fk_documents_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_documents_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT fk_documents_cash_session_id FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id)
);

CREATE TABLE document_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    original_line_id BIGINT,
    po_line_id BIGINT,
    product_id BIGINT,
    product_name VARCHAR(200) NOT NULL,
    product_name_ar VARCHAR(200),
    sku VARCHAR(80),
    barcode VARCHAR(100),
    category_name VARCHAR(100),
    unit_name VARCHAR(80),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    unit_price DECIMAL(24,6) NOT NULL CHECK(unit_price>=0),
    discount DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(discount>=0),
    tax_name VARCHAR(100),
    tax_rate DECIMAL(28,12) NOT NULL DEFAULT 0,
    net DECIMAL(24,6) NOT NULL,
    tax DECIMAL(24,6) NOT NULL,
    total DECIMAL(24,6) NOT NULL,
    base_net DECIMAL(24,6) NOT NULL,
    base_tax DECIMAL(24,6) NOT NULL,
    base_total DECIMAL(24,6) NOT NULL,
    cost_total DECIMAL(24,6) NOT NULL DEFAULT 0,
    cost_basis DECIMAL(24,6) NOT NULL DEFAULT 0,
    returned_qty DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(returned_qty>=0 AND returned_qty<=quantity),
    disposition VARCHAR(20),
    note VARCHAR(1000),
    CONSTRAINT fk_document_lines_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_document_lines_original_line_id FOREIGN KEY (original_line_id) REFERENCES document_lines(id),
    CONSTRAINT fk_document_lines_po_line_id FOREIGN KEY (po_line_id) REFERENCES po_lines(id),
    CONSTRAINT fk_document_lines_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    method_code VARCHAR(20) NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    amount DECIMAL(24,6) NOT NULL CHECK(amount>=0),
    base_amount DECIMAL(24,6) NOT NULL CHECK(base_amount>=0),
    tendered DECIMAL(24,6) NOT NULL CHECK(tendered>=0),
    change_amount DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(change_amount>=0),
    direction INTEGER NOT NULL CHECK(direction IN (-1,1)),
    reference VARCHAR(200),
    cash_session_id BIGINT,
    CONSTRAINT fk_payments_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_payments_method_code FOREIGN KEY (method_code) REFERENCES payment_methods(code),
    CONSTRAINT fk_payments_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code),
    CONSTRAINT fk_payments_cash_session_id FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id)
);

CREATE TABLE party_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    amount DECIMAL(24,6) NOT NULL,
    base_amount DECIMAL(24,6) NOT NULL,
    open_amount DECIMAL(24,6) NOT NULL,
    open_base DECIMAL(24,6) NOT NULL,
    due_date DATE,
    reminder_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_entries_party_id FOREIGN KEY (party_id) REFERENCES parties(id),
    CONSTRAINT fk_party_entries_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_party_entries_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code)
);

CREATE TABLE allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_entry_id BIGINT NOT NULL,
    invoice_entry_id BIGINT NOT NULL,
    amount DECIMAL(24,6) NOT NULL CHECK(amount>0),
    historical_base DECIMAL(24,6) NOT NULL,
    settlement_base DECIMAL(24,6) NOT NULL,
    fx_difference DECIMAL(24,6) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(settlement_entry_id<>invoice_entry_id),
    CONSTRAINT fk_allocations_settlement_entry_id FOREIGN KEY (settlement_entry_id) REFERENCES party_entries(id),
    CONSTRAINT fk_allocations_invoice_entry_id FOREIGN KEY (invoice_entry_id) REFERENCES party_entries(id)
);

CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    document_id BIGINT NOT NULL UNIQUE,
    journal_date DATE NOT NULL,
    description VARCHAR(2000) NOT NULL,
    reversal_of BIGINT,
    created_by BIGINT NOT NULL,
    posted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_journal_entries_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_journal_entries_reversal_of FOREIGN KEY (reversal_of) REFERENCES journal_entries(id),
    CONSTRAINT fk_journal_entries_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE journal_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    debit DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(debit>=0),
    credit DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(credit>=0),
    memo VARCHAR(1000),
    CHECK((debit>0 AND credit=0) OR (credit>0 AND debit=0)),
    CONSTRAINT fk_journal_lines_entry_id FOREIGN KEY (entry_id) REFERENCES journal_entries(id),
    CONSTRAINT fk_journal_lines_account_id FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    document_line_id BIGINT,
    movement_type VARCHAR(40) NOT NULL,
    quantity DECIMAL(24,6) NOT NULL,
    before_qty DECIMAL(24,6) NOT NULL,
    after_qty DECIMAL(24,6) NOT NULL,
    cost_value DECIMAL(24,6) NOT NULL,
    reason VARCHAR(1000),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(after_qty=before_qty+quantity),
    CONSTRAINT fk_stock_movements_product_id FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_stock_movements_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_stock_movements_document_line_id FOREIGN KEY (document_line_id) REFERENCES document_lines(id),
    CONSTRAINT fk_stock_movements_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE cost_layers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    movement_id BIGINT NOT NULL,
    original_quantity DECIMAL(24,6) NOT NULL CHECK(original_quantity>0),
    remaining_qty DECIMAL(24,6) NOT NULL CHECK(remaining_qty>=0),
    original_value DECIMAL(24,6) NOT NULL CHECK(original_value>=0),
    remaining_value DECIMAL(24,6) NOT NULL CHECK(remaining_value>=0),
    acquired_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(remaining_qty<=original_quantity),
    CONSTRAINT fk_cost_layers_product_id FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_cost_layers_movement_id FOREIGN KEY (movement_id) REFERENCES stock_movements(id)
);

CREATE TABLE cost_consumptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id BIGINT NOT NULL,
    layer_id BIGINT NOT NULL,
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    cost_value DECIMAL(24,6) NOT NULL CHECK(cost_value>=0),
    CONSTRAINT fk_cost_consumptions_movement_id FOREIGN KEY (movement_id) REFERENCES stock_movements(id),
    CONSTRAINT fk_cost_consumptions_layer_id FOREIGN KEY (layer_id) REFERENCES cost_layers(id)
);

CREATE TABLE cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    document_id BIGINT,
    movement_type VARCHAR(40) NOT NULL,
    amount DECIMAL(24,6) NOT NULL,
    reason VARCHAR(1000),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cash_movements_session_id FOREIGN KEY (session_id) REFERENCES cash_sessions(id),
    CONSTRAINT fk_cash_movements_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_cash_movements_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE held_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    party_id BIGINT,
    user_id BIGINT NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    discount_value DECIMAL(24,6) NOT NULL DEFAULT 0,
    discount_percent BOOLEAN NOT NULL DEFAULT FALSE,
    note VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_held_sales_party_id FOREIGN KEY (party_id) REFERENCES parties(id),
    CONSTRAINT fk_held_sales_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_held_sales_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code)
);

CREATE TABLE held_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    held_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    price DECIMAL(24,6) NOT NULL CHECK(price>=0),
    discount_value DECIMAL(24,6) NOT NULL DEFAULT 0,
    discount_percent BOOLEAN NOT NULL DEFAULT FALSE,
    note VARCHAR(1000),
    CONSTRAINT fk_held_lines_held_id FOREIGN KEY (held_id) REFERENCES held_sales(id),
    CONSTRAINT fk_held_lines_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE stock_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    posted_document_id BIGINT,
    CONSTRAINT fk_stock_counts_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_stock_counts_posted_document_id FOREIGN KEY (posted_document_id) REFERENCES documents(id)
);

CREATE TABLE stock_count_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    expected DECIMAL(24,6) NOT NULL,
    counted DECIMAL(24,6) NOT NULL CHECK(counted>=0),
    UNIQUE(count_id,product_id),
    CONSTRAINT fk_stock_count_lines_count_id FOREIGN KEY (count_id) REFERENCES stock_counts(id),
    CONSTRAINT fk_stock_count_lines_product_id FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE period_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    locked_by BIGINT NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK(start_date<=end_date),
    CONSTRAINT fk_period_locks_locked_by FOREIGN KEY (locked_by) REFERENCES users(id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_key VARCHAR(100) NOT NULL UNIQUE,
    kind VARCHAR(40) NOT NULL,
    entity_id BIGINT,
    message VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE notification_reads (
    notification_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY(notification_id,user_id),
    CONSTRAINT fk_notification_reads_notification_id FOREIGN KEY (notification_id) REFERENCES notifications(id),
    CONSTRAINT fk_notification_reads_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(60),
    entity_id BIGINT,
    old_summary VARCHAR(2000),
    new_summary VARCHAR(2000),
    reason VARCHAR(1000),
    approved_by BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user_id FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_audit_logs_approved_by FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE INDEX ix_products_0 ON products(name);
CREATE INDEX ix_products_1 ON products(name_ar);
CREATE INDEX ix_documents_2 ON documents(document_date);
CREATE INDEX ix_documents_3 ON documents(kind,document_date);
CREATE INDEX ix_documents_4 ON documents(party_id);
CREATE INDEX ix_documents_5 ON documents(original_id);
CREATE INDEX ix_document_lines_6 ON document_lines(document_id);
CREATE INDEX ix_document_lines_7 ON document_lines(product_id);
CREATE INDEX ix_document_lines_8 ON document_lines(original_line_id);
CREATE INDEX ix_payments_9 ON payments(document_id);
CREATE INDEX ix_party_entries_10 ON party_entries(party_id,due_date);
CREATE INDEX ix_stock_movements_11 ON stock_movements(product_id,id);
CREATE INDEX ix_cost_layers_12 ON cost_layers(product_id,id);
CREATE INDEX ix_journal_entries_13 ON journal_entries(journal_date);
CREATE INDEX ix_journal_lines_14 ON journal_lines(account_id,entry_id);
CREATE INDEX ix_parties_15 ON parties(name);
CREATE INDEX ix_parties_16 ON parties(phone);
CREATE INDEX ix_cash_movements_17 ON cash_movements(session_id);
CREATE INDEX ix_audit_logs_18 ON audit_logs(created_at);
CREATE INDEX ix_po_lines_19 ON po_lines(order_id);

CREATE VIEW sales AS SELECT * FROM documents WHERE kind='SALE';

CREATE VIEW sale_items AS SELECT l.* FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE d.kind='SALE';

CREATE VIEW sale_returns AS SELECT * FROM documents WHERE kind='SALE_RETURN';

CREATE VIEW purchases AS SELECT * FROM documents WHERE kind='PURCHASE';

CREATE VIEW purchase_returns AS SELECT * FROM documents WHERE kind='PURCHASE_RETURN';

CREATE VIEW customers AS SELECT * FROM parties WHERE kind='CUSTOMER';

CREATE VIEW suppliers AS SELECT * FROM parties WHERE kind='SUPPLIER';

CREATE VIEW v_sales_facts AS SELECT d.id AS document_id,d.document_date,d.kind,d.number,d.party_id,d.party_name,d.created_by,l.product_id,l.product_name,l.category_name,l.quantity*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS quantity,l.base_net*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS revenue,l.base_tax*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS tax,l.cost_total*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS cogs,l.discount*d.rate_to_base*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS discount FROM documents d JOIN document_lines l ON l.document_id=d.id WHERE d.kind IN ('SALE','SALE_RETURN');

-- Reference data only. Administrator and business settings are created by the wizard.
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('USD','US Dollar','$',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('LBP','Lebanese Pound','LBP',0);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('EUR','Euro','EUR',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('GBP','Pound Sterling','GBP',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('JPY','Yen','JPY',0);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('AED','UAE Dirham','AED',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('SAR','Saudi Riyal','SAR',2);
INSERT INTO roles(role_code,name) VALUES ('ADMIN','Admin');
INSERT INTO roles(role_code,name) VALUES ('CASHIER','Cashier');
INSERT INTO permissions(permission_code) VALUES ('POS_ACCESS');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'POS_ACCESS' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'POS_ACCESS' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('SALE_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_CREATE' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('SALE_VOID');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_VOID' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SALE_DISCOUNT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_DISCOUNT' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_DISCOUNT' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('SALE_LARGE_DISCOUNT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_LARGE_DISCOUNT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRICE_OVERRIDE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRICE_OVERRIDE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('RETURN_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'RETURN_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'RETURN_CREATE' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('RETURN_WITHOUT_RECEIPT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'RETURN_WITHOUT_RECEIPT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('REFUND_CASH');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REFUND_CASH' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_EDIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_EDIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_ARCHIVE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_ARCHIVE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_COST_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_COST_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('INVENTORY_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'INVENTORY_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('INVENTORY_ADJUST');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'INVENTORY_ADJUST' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PURCHASE_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PURCHASE_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PURCHASE_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PURCHASE_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SUPPLIER_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SUPPLIER_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('CUSTOMER_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_VIEW' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('CUSTOMER_EDIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_EDIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_EDIT' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('CUSTOMER_CREDIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_CREDIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_CREDIT' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('REPORT_SALES');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REPORT_SALES' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('REPORT_PROFIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REPORT_PROFIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('REPORT_ACCOUNTING');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REPORT_ACCOUNTING' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('EXPENSE_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'EXPENSE_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('EXPENSE_APPROVE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'EXPENSE_APPROVE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('ACCOUNTING_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'ACCOUNTING_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('ACCOUNTING_POST');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'ACCOUNTING_POST' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_GENERAL');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_GENERAL' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_TAX');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_TAX' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_CURRENCY');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_CURRENCY' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_USERS');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_USERS' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('BACKUP_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'BACKUP_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('BACKUP_RESTORE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'BACKUP_RESTORE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('AUDIT_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'AUDIT_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('CASH_SESSION');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CASH_SESSION' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CASH_SESSION' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('DEBT_RECEIVE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'DEBT_RECEIVE' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'DEBT_RECEIVE' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('DEBT_PAY');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'DEBT_PAY' FROM roles WHERE role_code='ADMIN';
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1110','Cash Register','الصندوق','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1120','Bank','المصرف','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1200','Accounts Receivable','ذمم العملاء','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1300','Inventory','المخزون','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1400','Input Tax','ضريبة المشتريات','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1410','Damaged Inventory','مخزون تالف','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('2100','Accounts Payable','ذمم الموردين','LIABILITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('2200','Output Tax','ضريبة المبيعات','LIABILITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('3100','Owner Capital','رأس المال','EQUITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('3200','Retained Earnings','أرباح محتجزة','EQUITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('3300','Owner Drawings','مسحوبات المالك','EQUITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('4100','Sales Revenue','إيرادات المبيعات','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('4200','Sales Returns','مردودات المبيعات','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('4300','Other Income','إيرادات أخرى','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('5100','Cost of Goods Sold','تكلفة البضاعة المباعة','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6100','Rent','الإيجار','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6200','Utilities','الخدمات','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6300','Salaries','الرواتب','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6400','Transport','النقل','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6500','Marketing','التسويق','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6600','Inventory Loss / Revaluation','فروقات المخزون','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6700','Other Expenses','مصاريف أخرى','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6800','Cash Over / Short','فروقات الصندوق','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7100','Realized FX Gain','ربح فرق العملة','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7200','Realized FX Loss','خسارة فرق العملة','EXPENSE',TRUE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('CASH','Cash','1110',TRUE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('CARD','Card','1120',FALSE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('BANK','Bank transfer','1120',FALSE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('OTHER','Other','1120',FALSE);
INSERT INTO app_settings(setting_key,setting_value) VALUES ('base_currency','USD');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('language','en');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('time_zone','Asia/Beirut');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('costing','WAC');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('tax_mode','NONE');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('allow_negative','false');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('allow_credit','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('enable_hold','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('enable_split','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('auto_print','false');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('price_override','PERMISSION');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('max_cashier_discount','10');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('refund_approval','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('cash_tolerance','1');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('due_soon_days','7');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('backup_exit','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('backup_daily','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('backup_keep','14');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('session_minutes','15');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('receipt_width','80');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('receipt_language','en');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('secondary_currency','');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('invoice_prefix','INV');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('theme','LIGHT');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('date_format','yyyy-MM-dd');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.cash','1110');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.bank','1120');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.ar','1200');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.inventory','1300');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.input_tax','1400');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.damaged','1410');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.ap','2100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.tax','2200');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.capital','3100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.drawings','3300');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.revenue','4100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.returns','4200');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.cogs','5100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.inventory_loss','6600');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.expense','6700');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.cash_difference','6800');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_gain','7100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_loss','7200');
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('SALE',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('PURCHASE',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('SALE_RETURN',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('PURCHASE_RETURN',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('CUSTOMER_PAYMENT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('SUPPLIER_PAYMENT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('EXPENSE',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('CASH_IN',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('CASH_OUT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('OPENING',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('ADJUSTMENT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('MANUAL',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('REVERSAL',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('JOURNAL',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('PO',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('HELD',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('COUNT',1);
INSERT INTO tax_rates(name,rate) VALUES ('Exempt',0);
INSERT INTO categories(name,name_ar) VALUES ('Other','أخرى');
INSERT INTO categories(name,name_ar) VALUES ('Food','مأكولات');
INSERT INTO categories(name,name_ar) VALUES ('Drinks','مشروبات');
INSERT INTO categories(name,name_ar) VALUES ('Electronics','إلكترونيات');
INSERT INTO categories(name,name_ar) VALUES ('Clothing','ملابس');
INSERT INTO units(name,name_ar,fractional) VALUES ('Piece','قطعة',FALSE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Kg','كغ',TRUE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Liter','ليتر',TRUE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Meter','متر',TRUE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Box','علبة',FALSE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1130','Exchange Clearing','تسوية الاستبدال','ASSET',TRUE);
INSERT INTO payment_methods(code,name,account_code,active,is_cash) VALUES ('EXCHANGE','Exchange credit','1130',TRUE,FALSE);

-- Accounting controls added without rewriting the protected original schema.

CREATE TABLE fx_revaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valuation_date DATE NOT NULL,
    currency_code VARCHAR(10) NOT NULL,
    document_id BIGINT NOT NULL UNIQUE,
    status VARCHAR(12) NOT NULL CHECK(status IN ('POSTED','REVERSED')),
    reversed_by_document_id BIGINT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(valuation_date,currency_code),
    CONSTRAINT fk_fx_revaluations_currency_code FOREIGN KEY (currency_code) REFERENCES currencies(code),
    CONSTRAINT fk_fx_revaluations_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_fx_revaluations_reversed_by_document_id FOREIGN KEY (reversed_by_document_id) REFERENCES documents(id),
    CONSTRAINT fk_fx_revaluations_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE fx_revaluation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revaluation_id BIGINT NOT NULL,
    party_entry_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    open_amount DECIMAL(24,6) NOT NULL,
    previous_open_base DECIMAL(24,6) NOT NULL,
    closing_open_base DECIMAL(24,6) NOT NULL,
    difference DECIMAL(24,6) NOT NULL,
    UNIQUE(revaluation_id,party_entry_id),
    CONSTRAINT fk_fx_revaluation_lines_revaluation_id FOREIGN KEY (revaluation_id) REFERENCES fx_revaluations(id),
    CONSTRAINT fk_fx_revaluation_lines_party_entry_id FOREIGN KEY (party_entry_id) REFERENCES party_entries(id),
    CONSTRAINT fk_fx_revaluation_lines_party_id FOREIGN KEY (party_id) REFERENCES parties(id)
);

CREATE TABLE inventory_revaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE,
    product_id BIGINT NOT NULL,
    old_value DECIMAL(24,6) NOT NULL,
    new_value DECIMAL(24,6) NOT NULL CHECK(new_value>=0),
    reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventory_revaluations_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_inventory_revaluations_product_id FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_inventory_revaluations_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE damaged_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    source_document_line_id BIGINT NOT NULL UNIQUE,
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    remaining_quantity DECIMAL(24,6) NOT NULL CHECK(remaining_quantity>=0),
    historical_cost DECIMAL(24,6) NOT NULL CHECK(historical_cost>=0),
    carrying_value DECIMAL(24,6) NOT NULL CHECK(carrying_value>=0),
    status VARCHAR(12) NOT NULL CHECK(status IN ('PENDING','VALUED','DISPOSED')),
    CHECK(remaining_quantity<=quantity),
    CONSTRAINT fk_damaged_inventory_product_id FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_damaged_inventory_source_document_line_id FOREIGN KEY (source_document_line_id) REFERENCES document_lines(id)
);

CREATE TABLE damaged_inventory_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    damaged_inventory_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    event_type VARCHAR(12) NOT NULL CHECK(event_type IN ('VALUATION','DISPOSAL')),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>=0),
    value_change DECIMAL(24,6) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_damaged_inventory_events_damaged_inventory_id FOREIGN KEY (damaged_inventory_id) REFERENCES damaged_inventory(id),
    CONSTRAINT fk_damaged_inventory_events_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_damaged_inventory_events_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE card_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE,
    settlement_date DATE NOT NULL,
    gross_amount DECIMAL(24,6) NOT NULL CHECK(gross_amount>0),
    fee_net DECIMAL(24,6) NOT NULL CHECK(fee_net>=0),
    fee_tax DECIMAL(24,6) NOT NULL CHECK(fee_tax>=0),
    net_deposit DECIMAL(24,6) NOT NULL CHECK(net_deposit>=0),
    reference VARCHAR(200),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(net_deposit+fee_net+fee_tax=gross_amount),
    CONSTRAINT fk_card_settlements_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_card_settlements_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE period_closures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    document_id BIGINT NOT NULL UNIQUE,
    lock_id BIGINT,
    status VARCHAR(12) NOT NULL CHECK(status IN ('POSTED','REVERSED')),
    reversed_by_document_id BIGINT,
    reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(start_date<=end_date),
    CONSTRAINT fk_period_closures_document_id FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_period_closures_lock_id FOREIGN KEY (lock_id) REFERENCES period_locks(id),
    CONSTRAINT fk_period_closures_reversed_by_document_id FOREIGN KEY (reversed_by_document_id) REFERENCES documents(id),
    CONSTRAINT fk_period_closures_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX ix_fx_revaluation_lines_entry ON fx_revaluation_lines(party_entry_id);
CREATE INDEX ix_damaged_inventory_product ON damaged_inventory(product_id,status);
CREATE INDEX ix_period_closures_dates ON period_closures(start_date,end_date,status);

INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1140','Supplier Advances','سلف الموردين','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1150','Card Clearing','تسوية البطاقات','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('2110','Customer Advances','دفعات العملاء المقدمة','LIABILITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6710','Card Processing Fees','عمولات البطاقات','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7110','Unrealized FX Gain','ربح عملة غير محقق','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7210','Unrealized FX Loss','خسارة عملة غير محققة','EXPENSE',TRUE);

INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.supplier_advances','1140');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.card_clearing','1150');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.customer_advances','2110');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.card_fee','6710');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_unrealized_gain','7110');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_unrealized_loss','7210');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.retained_earnings','3200');

UPDATE payment_methods SET account_code='1150' WHERE code='CARD';

INSERT INTO schema_version(version_no,checksum) VALUES (1,'7a8f9e4f1bb79882e970b5257a581d6f90e0fc43531091c60c692d96c404447c');
INSERT INTO schema_version(version_no,checksum) VALUES (2,'a4bfe639ab75fb6b9c61767bab3e33d06351345c5b67d529391ae1e9bf9015bc');
INSERT INTO schema_version(version_no,checksum) VALUES (3,'04bae980c9c19bc10341c5d71b0c4b122ae108dcdc8cb8aa1bdbef0ea368f422');
