-- Professional POS schema v1. Amounts use exact decimals; FX is base units per 1 foreign unit.

CREATE TABLE schema_version (
    version_no INTEGER PRIMARY KEY,
    checksum VARCHAR(64) NOT NULL,
    installed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_settings (
    setting_key VARCHAR(100) PRIMARY KEY,
    setting_value VARCHAR(4000) NOT NULL
);

CREATE TABLE business_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name VARCHAR(200) NOT NULL,
    legal_name VARCHAR(200),
    address VARCHAR(1000),
    phone VARCHAR(80),
    email VARCHAR(200),
    tax_number VARCHAR(100),
    country VARCHAR(100),
    time_zone VARCHAR(80) NOT NULL,
    footer VARCHAR(1000),
    logo_path VARCHAR(1000)
);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE permissions (
    permission_code VARCHAR(60) PRIMARY KEY
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id),
    permission_code VARCHAR(60) NOT NULL REFERENCES permissions(permission_code),
    PRIMARY KEY(role_id,permission_code)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL UNIQUE,
    full_name VARCHAR(200) NOT NULL,
    password_hash VARCHAR(512) NOT NULL,
    role_id BIGINT NOT NULL REFERENCES roles(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    last_login TIMESTAMP,
    must_change BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE currencies (
    code VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    symbol VARCHAR(20) NOT NULL,
    decimal_places INTEGER NOT NULL CHECK(decimal_places BETWEEN 0 AND 6),
    symbol_before BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    effective_date DATE NOT NULL,
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(currency_code,effective_date)
);

CREATE TABLE tax_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    rate DECIMAL(28,12) NOT NULL CHECK(rate>=0 AND rate<=100),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    name_ar VARCHAR(100),
    tax_id BIGINT REFERENCES tax_rates(id),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    name_ar VARCHAR(80),
    fractional BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(12) NOT NULL CHECK(kind IN ('CUSTOMER','SUPPLIER')),
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    company VARCHAR(200),
    contact VARCHAR(200),
    phone VARCHAR(80),
    email VARCHAR(200),
    address VARCHAR(1000),
    tax_number VARCHAR(100),
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    credit_limit DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(credit_limit>=0),
    terms_days INTEGER NOT NULL DEFAULT 0 CHECK(terms_days>=0),
    discount_pct DECIMAL(28,12) NOT NULL DEFAULT 0 CHECK(discount_pct BETWEEN 0 AND 100),
    notes VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    name_ar VARCHAR(200),
    description VARCHAR(2000),
    brand VARCHAR(100),
    category_id BIGINT REFERENCES categories(id),
    unit_id BIGINT NOT NULL REFERENCES units(id),
    tax_id BIGINT NOT NULL REFERENCES tax_rates(id),
    preferred_supplier_id BIGINT REFERENCES parties(id),
    parent_product_id BIGINT REFERENCES products(id),
    variant_label VARCHAR(200),
    price DECIMAL(24,6) NOT NULL CHECK(price>=0),
    wholesale_price DECIMAL(24,6),
    current_cost DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(current_cost>=0),
    last_cost DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(last_cost>=0),
    on_hand DECIMAL(24,6) NOT NULL DEFAULT 0,
    stock_value DECIMAL(24,6) NOT NULL DEFAULT 0,
    min_stock DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(min_stock>=0),
    reorder_level DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(reorder_level>=0),
    max_stock DECIMAL(24,6),
    track_stock BOOLEAN NOT NULL DEFAULT TRUE,
    allow_negative BOOLEAN NOT NULL DEFAULT FALSE,
    fractional BOOLEAN NOT NULL DEFAULT FALSE,
    favorite BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_barcodes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    barcode VARCHAR(100) NOT NULL UNIQUE,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    old_price DECIMAL(24,6) NOT NULL,
    new_price DECIMAL(24,6) NOT NULL,
    old_cost DECIMAL(24,6) NOT NULL,
    new_cost DECIMAL(24,6) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    reason VARCHAR(1000) NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    name_ar VARCHAR(150),
    account_type VARCHAR(12) NOT NULL CHECK(account_type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')),
    parent_id BIGINT REFERENCES accounts(id),
    system_account BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE payment_methods (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    account_code VARCHAR(20) NOT NULL REFERENCES accounts(code),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    is_cash BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE document_sequences (
    sequence_code VARCHAR(30) PRIMARY KEY,
    next_value BIGINT NOT NULL CHECK(next_value>0)
);

CREATE TABLE cash_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    opened_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP,
    opening_cash DECIMAL(24,6) NOT NULL CHECK(opening_cash>=0),
    expected_cash DECIMAL(24,6),
    counted_cash DECIMAL(24,6),
    difference DECIMAL(24,6),
    notes VARCHAR(2000)
);

CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    supplier_id BIGINT NOT NULL REFERENCES parties(id),
    ordered_on DATE NOT NULL,
    expected_on DATE,
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    status VARCHAR(25) NOT NULL CHECK(status IN ('DRAFT','SENT','PARTIALLY_RECEIVED','RECEIVED','CANCELLED')),
    notes VARCHAR(2000),
    created_by BIGINT NOT NULL REFERENCES users(id)
);

CREATE TABLE po_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES purchase_orders(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    received_qty DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(received_qty>=0 AND received_qty<=quantity),
    unit_cost DECIMAL(24,6) NOT NULL CHECK(unit_cost>=0),
    discount_pct DECIMAL(28,12) NOT NULL DEFAULT 0 CHECK(discount_pct BETWEEN 0 AND 100),
    tax_rate DECIMAL(28,12) NOT NULL DEFAULT 0 CHECK(tax_rate BETWEEN 0 AND 100)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(30) NOT NULL CHECK(kind IN ('SALE','PURCHASE','SALE_RETURN','PURCHASE_RETURN','CUSTOMER_PAYMENT','SUPPLIER_PAYMENT','EXPENSE','CASH_IN','CASH_OUT','OPENING','ADJUSTMENT','MANUAL','REVERSAL')),
    number VARCHAR(40) NOT NULL UNIQUE,
    request_key VARCHAR(80) NOT NULL UNIQUE,
    original_id BIGINT REFERENCES documents(id),
    exchange_id VARCHAR(80),
    order_id BIGINT REFERENCES purchase_orders(id),
    party_id BIGINT REFERENCES parties(id),
    party_name VARCHAR(200),
    party_address VARCHAR(1000),
    party_tax_number VARCHAR(100),
    document_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_date DATE,
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    subtotal DECIMAL(24,6) NOT NULL DEFAULT 0,
    discount DECIMAL(24,6) NOT NULL DEFAULT 0,
    net DECIMAL(24,6) NOT NULL DEFAULT 0,
    tax DECIMAL(24,6) NOT NULL DEFAULT 0,
    total DECIMAL(24,6) NOT NULL DEFAULT 0,
    base_net DECIMAL(24,6) NOT NULL DEFAULT 0,
    base_tax DECIMAL(24,6) NOT NULL DEFAULT 0,
    base_total DECIMAL(24,6) NOT NULL DEFAULT 0,
    cogs DECIMAL(24,6) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    reference VARCHAR(200),
    notes VARCHAR(2000),
    reason VARCHAR(1000),
    store_name VARCHAR(200),
    store_address VARCHAR(1000),
    store_phone VARCHAR(80),
    store_tax_number VARCHAR(100),
    logo_path VARCHAR(1000),
    footer VARCHAR(1000),
    created_by BIGINT NOT NULL REFERENCES users(id),
    approved_by BIGINT REFERENCES users(id),
    cash_session_id BIGINT REFERENCES cash_sessions(id)
);

CREATE TABLE document_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    original_line_id BIGINT REFERENCES document_lines(id),
    po_line_id BIGINT REFERENCES po_lines(id),
    product_id BIGINT REFERENCES products(id),
    product_name VARCHAR(200) NOT NULL,
    product_name_ar VARCHAR(200),
    sku VARCHAR(80),
    barcode VARCHAR(100),
    category_name VARCHAR(100),
    unit_name VARCHAR(80),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    unit_price DECIMAL(24,6) NOT NULL CHECK(unit_price>=0),
    discount DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(discount>=0),
    tax_name VARCHAR(100),
    tax_rate DECIMAL(28,12) NOT NULL DEFAULT 0,
    net DECIMAL(24,6) NOT NULL,
    tax DECIMAL(24,6) NOT NULL,
    total DECIMAL(24,6) NOT NULL,
    base_net DECIMAL(24,6) NOT NULL,
    base_tax DECIMAL(24,6) NOT NULL,
    base_total DECIMAL(24,6) NOT NULL,
    cost_total DECIMAL(24,6) NOT NULL DEFAULT 0,
    cost_basis DECIMAL(24,6) NOT NULL DEFAULT 0,
    returned_qty DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(returned_qty>=0 AND returned_qty<=quantity),
    disposition VARCHAR(20),
    note VARCHAR(1000)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES documents(id),
    method_code VARCHAR(20) NOT NULL REFERENCES payment_methods(code),
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    rate_to_base DECIMAL(28,12) NOT NULL CHECK(rate_to_base>0),
    amount DECIMAL(24,6) NOT NULL CHECK(amount>=0),
    base_amount DECIMAL(24,6) NOT NULL CHECK(base_amount>=0),
    tendered DECIMAL(24,6) NOT NULL CHECK(tendered>=0),
    change_amount DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(change_amount>=0),
    direction INTEGER NOT NULL CHECK(direction IN (-1,1)),
    reference VARCHAR(200),
    cash_session_id BIGINT REFERENCES cash_sessions(id)
);

CREATE TABLE party_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    party_id BIGINT NOT NULL REFERENCES parties(id),
    document_id BIGINT NOT NULL REFERENCES documents(id),
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    amount DECIMAL(24,6) NOT NULL,
    base_amount DECIMAL(24,6) NOT NULL,
    open_amount DECIMAL(24,6) NOT NULL,
    open_base DECIMAL(24,6) NOT NULL,
    due_date DATE,
    reminder_date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    settlement_entry_id BIGINT NOT NULL REFERENCES party_entries(id),
    invoice_entry_id BIGINT NOT NULL REFERENCES party_entries(id),
    amount DECIMAL(24,6) NOT NULL CHECK(amount>0),
    historical_base DECIMAL(24,6) NOT NULL,
    settlement_base DECIMAL(24,6) NOT NULL,
    fx_difference DECIMAL(24,6) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(settlement_entry_id<>invoice_entry_id)
);

CREATE TABLE journal_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id),
    journal_date DATE NOT NULL,
    description VARCHAR(2000) NOT NULL,
    reversal_of BIGINT REFERENCES journal_entries(id),
    created_by BIGINT NOT NULL REFERENCES users(id),
    posted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE journal_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id BIGINT NOT NULL REFERENCES journal_entries(id),
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    debit DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(debit>=0),
    credit DECIMAL(24,6) NOT NULL DEFAULT 0 CHECK(credit>=0),
    memo VARCHAR(1000),
    CHECK((debit>0 AND credit=0) OR (credit>0 AND debit=0))
);

CREATE TABLE stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    document_id BIGINT NOT NULL REFERENCES documents(id),
    document_line_id BIGINT REFERENCES document_lines(id),
    movement_type VARCHAR(40) NOT NULL,
    quantity DECIMAL(24,6) NOT NULL,
    before_qty DECIMAL(24,6) NOT NULL,
    after_qty DECIMAL(24,6) NOT NULL,
    cost_value DECIMAL(24,6) NOT NULL,
    reason VARCHAR(1000),
    user_id BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(after_qty=before_qty+quantity)
);

CREATE TABLE cost_layers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    movement_id BIGINT NOT NULL REFERENCES stock_movements(id),
    original_quantity DECIMAL(24,6) NOT NULL CHECK(original_quantity>0),
    remaining_qty DECIMAL(24,6) NOT NULL CHECK(remaining_qty>=0),
    original_value DECIMAL(24,6) NOT NULL CHECK(original_value>=0),
    remaining_value DECIMAL(24,6) NOT NULL CHECK(remaining_value>=0),
    acquired_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(remaining_qty<=original_quantity)
);

CREATE TABLE cost_consumptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_id BIGINT NOT NULL REFERENCES stock_movements(id),
    layer_id BIGINT NOT NULL REFERENCES cost_layers(id),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    cost_value DECIMAL(24,6) NOT NULL CHECK(cost_value>=0)
);

CREATE TABLE cash_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES cash_sessions(id),
    document_id BIGINT REFERENCES documents(id),
    movement_type VARCHAR(40) NOT NULL,
    amount DECIMAL(24,6) NOT NULL,
    reason VARCHAR(1000),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE held_sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    party_id BIGINT REFERENCES parties(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    discount_value DECIMAL(24,6) NOT NULL DEFAULT 0,
    discount_percent BOOLEAN NOT NULL DEFAULT FALSE,
    note VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE held_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    held_id BIGINT NOT NULL REFERENCES held_sales(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    price DECIMAL(24,6) NOT NULL CHECK(price>=0),
    discount_value DECIMAL(24,6) NOT NULL DEFAULT 0,
    discount_percent BOOLEAN NOT NULL DEFAULT FALSE,
    note VARCHAR(1000)
);

CREATE TABLE stock_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(40) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    posted_document_id BIGINT REFERENCES documents(id)
);

CREATE TABLE stock_count_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    count_id BIGINT NOT NULL REFERENCES stock_counts(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    expected DECIMAL(24,6) NOT NULL,
    counted DECIMAL(24,6) NOT NULL CHECK(counted>=0),
    UNIQUE(count_id,product_id)
);

CREATE TABLE period_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    locked_by BIGINT NOT NULL REFERENCES users(id),
    reason VARCHAR(1000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK(start_date<=end_date)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_key VARCHAR(100) NOT NULL UNIQUE,
    kind VARCHAR(40) NOT NULL,
    entity_id BIGINT,
    message VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE notification_reads (
    notification_id BIGINT NOT NULL REFERENCES notifications(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY(notification_id,user_id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(60),
    entity_id BIGINT,
    old_summary VARCHAR(2000),
    new_summary VARCHAR(2000),
    reason VARCHAR(1000),
    approved_by BIGINT REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_products_0 ON products(name);
CREATE INDEX ix_products_1 ON products(name_ar);
CREATE INDEX ix_documents_2 ON documents(document_date);
CREATE INDEX ix_documents_3 ON documents(kind,document_date);
CREATE INDEX ix_documents_4 ON documents(party_id);
CREATE INDEX ix_documents_5 ON documents(original_id);
CREATE INDEX ix_document_lines_6 ON document_lines(document_id);
CREATE INDEX ix_document_lines_7 ON document_lines(product_id);
CREATE INDEX ix_document_lines_8 ON document_lines(original_line_id);
CREATE INDEX ix_payments_9 ON payments(document_id);
CREATE INDEX ix_party_entries_10 ON party_entries(party_id,due_date);
CREATE INDEX ix_stock_movements_11 ON stock_movements(product_id,id);
CREATE INDEX ix_cost_layers_12 ON cost_layers(product_id,id);
CREATE INDEX ix_journal_entries_13 ON journal_entries(journal_date);
CREATE INDEX ix_journal_lines_14 ON journal_lines(account_id,entry_id);
CREATE INDEX ix_parties_15 ON parties(name);
CREATE INDEX ix_parties_16 ON parties(phone);
CREATE INDEX ix_cash_movements_17 ON cash_movements(session_id);
CREATE INDEX ix_audit_logs_18 ON audit_logs(created_at);
CREATE INDEX ix_po_lines_19 ON po_lines(order_id);

CREATE VIEW sales AS SELECT * FROM documents WHERE kind='SALE';

CREATE VIEW sale_items AS SELECT l.* FROM document_lines l JOIN documents d ON d.id=l.document_id WHERE d.kind='SALE';

CREATE VIEW sale_returns AS SELECT * FROM documents WHERE kind='SALE_RETURN';

CREATE VIEW purchases AS SELECT * FROM documents WHERE kind='PURCHASE';

CREATE VIEW purchase_returns AS SELECT * FROM documents WHERE kind='PURCHASE_RETURN';

CREATE VIEW customers AS SELECT * FROM parties WHERE kind='CUSTOMER';

CREATE VIEW suppliers AS SELECT * FROM parties WHERE kind='SUPPLIER';

CREATE VIEW v_sales_facts AS SELECT d.id AS document_id,d.document_date,d.kind,d.number,d.party_id,d.party_name,d.created_by,l.product_id,l.product_name,l.category_name,l.quantity*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS quantity,l.base_net*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS revenue,l.base_tax*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS tax,l.cost_total*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS cogs,l.discount*d.rate_to_base*CASE WHEN d.kind='SALE' THEN 1 ELSE -1 END AS discount FROM documents d JOIN document_lines l ON l.document_id=d.id WHERE d.kind IN ('SALE','SALE_RETURN');
