-- Reference data only. Administrator and business settings are created by the wizard.
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('USD','US Dollar','$',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('LBP','Lebanese Pound','LBP',0);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('EUR','Euro','EUR',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('GBP','Pound Sterling','GBP',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('JPY','Yen','JPY',0);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('AED','UAE Dirham','AED',2);
INSERT INTO currencies(code,name,symbol,decimal_places) VALUES ('SAR','Saudi Riyal','SAR',2);
INSERT INTO roles(role_code,name) VALUES ('ADMIN','Admin');
INSERT INTO roles(role_code,name) VALUES ('CASHIER','Cashier');
INSERT INTO permissions(permission_code) VALUES ('POS_ACCESS');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'POS_ACCESS' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'POS_ACCESS' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('SALE_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_CREATE' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('SALE_VOID');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_VOID' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SALE_DISCOUNT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_DISCOUNT' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_DISCOUNT' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('SALE_LARGE_DISCOUNT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SALE_LARGE_DISCOUNT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRICE_OVERRIDE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRICE_OVERRIDE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('RETURN_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'RETURN_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'RETURN_CREATE' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('RETURN_WITHOUT_RECEIPT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'RETURN_WITHOUT_RECEIPT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('REFUND_CASH');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REFUND_CASH' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_EDIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_EDIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_ARCHIVE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_ARCHIVE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PRODUCT_COST_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PRODUCT_COST_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('INVENTORY_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'INVENTORY_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('INVENTORY_ADJUST');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'INVENTORY_ADJUST' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PURCHASE_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PURCHASE_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('PURCHASE_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'PURCHASE_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SUPPLIER_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SUPPLIER_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('CUSTOMER_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_VIEW' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('CUSTOMER_EDIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_EDIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_EDIT' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('CUSTOMER_CREDIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_CREDIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CUSTOMER_CREDIT' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('REPORT_SALES');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REPORT_SALES' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('REPORT_PROFIT');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REPORT_PROFIT' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('REPORT_ACCOUNTING');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'REPORT_ACCOUNTING' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('EXPENSE_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'EXPENSE_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('EXPENSE_APPROVE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'EXPENSE_APPROVE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('ACCOUNTING_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'ACCOUNTING_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('ACCOUNTING_POST');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'ACCOUNTING_POST' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_GENERAL');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_GENERAL' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_TAX');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_TAX' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_CURRENCY');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_CURRENCY' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('SETTINGS_USERS');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'SETTINGS_USERS' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('BACKUP_CREATE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'BACKUP_CREATE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('BACKUP_RESTORE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'BACKUP_RESTORE' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('AUDIT_VIEW');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'AUDIT_VIEW' FROM roles WHERE role_code='ADMIN';
INSERT INTO permissions(permission_code) VALUES ('CASH_SESSION');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CASH_SESSION' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'CASH_SESSION' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('DEBT_RECEIVE');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'DEBT_RECEIVE' FROM roles WHERE role_code='ADMIN';
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'DEBT_RECEIVE' FROM roles WHERE role_code='CASHIER';
INSERT INTO permissions(permission_code) VALUES ('DEBT_PAY');
INSERT INTO role_permissions(role_id,permission_code) SELECT id,'DEBT_PAY' FROM roles WHERE role_code='ADMIN';
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1110','Cash Register','الصندوق','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1120','Bank','المصرف','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1200','Accounts Receivable','ذمم العملاء','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1300','Inventory','المخزون','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1400','Input Tax','ضريبة المشتريات','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1410','Damaged Inventory','مخزون تالف','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('2100','Accounts Payable','ذمم الموردين','LIABILITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('2200','Output Tax','ضريبة المبيعات','LIABILITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('3100','Owner Capital','رأس المال','EQUITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('3200','Retained Earnings','أرباح محتجزة','EQUITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('3300','Owner Drawings','مسحوبات المالك','EQUITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('4100','Sales Revenue','إيرادات المبيعات','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('4200','Sales Returns','مردودات المبيعات','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('4300','Other Income','إيرادات أخرى','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('5100','Cost of Goods Sold','تكلفة البضاعة المباعة','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6100','Rent','الإيجار','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6200','Utilities','الخدمات','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6300','Salaries','الرواتب','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6400','Transport','النقل','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6500','Marketing','التسويق','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6600','Inventory Loss / Revaluation','فروقات المخزون','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6700','Other Expenses','مصاريف أخرى','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6800','Cash Over / Short','فروقات الصندوق','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7100','Realized FX Gain','ربح فرق العملة','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7200','Realized FX Loss','خسارة فرق العملة','EXPENSE',TRUE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('CASH','Cash','1110',TRUE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('CARD','Card','1120',FALSE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('BANK','Bank transfer','1120',FALSE);
INSERT INTO payment_methods(code,name,account_code,is_cash) VALUES ('OTHER','Other','1120',FALSE);
INSERT INTO app_settings(setting_key,setting_value) VALUES ('base_currency','USD');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('language','en');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('time_zone','Asia/Beirut');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('costing','WAC');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('tax_mode','NONE');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('allow_negative','false');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('allow_credit','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('enable_hold','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('enable_split','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('auto_print','false');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('price_override','PERMISSION');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('max_cashier_discount','10');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('refund_approval','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('cash_tolerance','1');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('due_soon_days','7');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('backup_exit','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('backup_daily','true');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('backup_keep','14');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('session_minutes','15');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('receipt_width','80');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('receipt_language','en');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('secondary_currency','');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('invoice_prefix','INV');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('theme','LIGHT');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('date_format','yyyy-MM-dd');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.cash','1110');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.bank','1120');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.ar','1200');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.inventory','1300');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.input_tax','1400');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.damaged','1410');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.ap','2100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.tax','2200');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.capital','3100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.drawings','3300');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.revenue','4100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.returns','4200');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.cogs','5100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.inventory_loss','6600');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.expense','6700');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.cash_difference','6800');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_gain','7100');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_loss','7200');
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('SALE',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('PURCHASE',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('SALE_RETURN',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('PURCHASE_RETURN',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('CUSTOMER_PAYMENT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('SUPPLIER_PAYMENT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('EXPENSE',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('CASH_IN',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('CASH_OUT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('OPENING',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('ADJUSTMENT',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('MANUAL',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('REVERSAL',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('JOURNAL',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('PO',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('HELD',1);
INSERT INTO document_sequences(sequence_code,next_value) VALUES ('COUNT',1);
INSERT INTO tax_rates(name,rate) VALUES ('Exempt',0);
INSERT INTO categories(name,name_ar) VALUES ('Other','أخرى');
INSERT INTO categories(name,name_ar) VALUES ('Food','مأكولات');
INSERT INTO categories(name,name_ar) VALUES ('Drinks','مشروبات');
INSERT INTO categories(name,name_ar) VALUES ('Electronics','إلكترونيات');
INSERT INTO categories(name,name_ar) VALUES ('Clothing','ملابس');
INSERT INTO units(name,name_ar,fractional) VALUES ('Piece','قطعة',FALSE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Kg','كغ',TRUE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Liter','ليتر',TRUE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Meter','متر',TRUE);
INSERT INTO units(name,name_ar,fractional) VALUES ('Box','علبة',FALSE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1130','Exchange Clearing','تسوية الاستبدال','ASSET',TRUE);
INSERT INTO payment_methods(code,name,account_code,active,is_cash) VALUES ('EXCHANGE','Exchange credit','1130',TRUE,FALSE);
