-- Accounting controls added without rewriting the protected original schema.

CREATE TABLE fx_revaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valuation_date DATE NOT NULL,
    currency_code VARCHAR(10) NOT NULL REFERENCES currencies(code),
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id),
    status VARCHAR(12) NOT NULL CHECK(status IN ('POSTED','REVERSED')),
    reversed_by_document_id BIGINT REFERENCES documents(id),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(valuation_date,currency_code)
);

CREATE TABLE fx_revaluation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revaluation_id BIGINT NOT NULL REFERENCES fx_revaluations(id),
    party_entry_id BIGINT NOT NULL REFERENCES party_entries(id),
    party_id BIGINT NOT NULL REFERENCES parties(id),
    open_amount DECIMAL(24,6) NOT NULL,
    previous_open_base DECIMAL(24,6) NOT NULL,
    closing_open_base DECIMAL(24,6) NOT NULL,
    difference DECIMAL(24,6) NOT NULL,
    UNIQUE(revaluation_id,party_entry_id)
);

CREATE TABLE inventory_revaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    old_value DECIMAL(24,6) NOT NULL,
    new_value DECIMAL(24,6) NOT NULL CHECK(new_value>=0),
    reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE damaged_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    source_document_line_id BIGINT NOT NULL UNIQUE REFERENCES document_lines(id),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>0),
    remaining_quantity DECIMAL(24,6) NOT NULL CHECK(remaining_quantity>=0),
    historical_cost DECIMAL(24,6) NOT NULL CHECK(historical_cost>=0),
    carrying_value DECIMAL(24,6) NOT NULL CHECK(carrying_value>=0),
    status VARCHAR(12) NOT NULL CHECK(status IN ('PENDING','VALUED','DISPOSED')),
    CHECK(remaining_quantity<=quantity)
);

CREATE TABLE damaged_inventory_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    damaged_inventory_id BIGINT NOT NULL REFERENCES damaged_inventory(id),
    document_id BIGINT NOT NULL REFERENCES documents(id),
    event_type VARCHAR(12) NOT NULL CHECK(event_type IN ('VALUATION','DISPOSAL')),
    quantity DECIMAL(24,6) NOT NULL CHECK(quantity>=0),
    value_change DECIMAL(24,6) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE card_settlements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id),
    settlement_date DATE NOT NULL,
    gross_amount DECIMAL(24,6) NOT NULL CHECK(gross_amount>0),
    fee_net DECIMAL(24,6) NOT NULL CHECK(fee_net>=0),
    fee_tax DECIMAL(24,6) NOT NULL CHECK(fee_tax>=0),
    net_deposit DECIMAL(24,6) NOT NULL CHECK(net_deposit>=0),
    reference VARCHAR(200),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(net_deposit+fee_net+fee_tax=gross_amount)
);

CREATE TABLE period_closures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    document_id BIGINT NOT NULL UNIQUE REFERENCES documents(id),
    lock_id BIGINT REFERENCES period_locks(id),
    status VARCHAR(12) NOT NULL CHECK(status IN ('POSTED','REVERSED')),
    reversed_by_document_id BIGINT REFERENCES documents(id),
    reason VARCHAR(1000) NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK(start_date<=end_date)
);

CREATE INDEX ix_fx_revaluation_lines_entry ON fx_revaluation_lines(party_entry_id);
CREATE INDEX ix_damaged_inventory_product ON damaged_inventory(product_id,status);
CREATE INDEX ix_period_closures_dates ON period_closures(start_date,end_date,status);

INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1140','Supplier Advances','سلف الموردين','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('1150','Card Clearing','تسوية البطاقات','ASSET',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('2110','Customer Advances','دفعات العملاء المقدمة','LIABILITY',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('6710','Card Processing Fees','عمولات البطاقات','EXPENSE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7110','Unrealized FX Gain','ربح عملة غير محقق','REVENUE',TRUE);
INSERT INTO accounts(code,name,name_ar,account_type,system_account) VALUES ('7210','Unrealized FX Loss','خسارة عملة غير محققة','EXPENSE',TRUE);

INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.supplier_advances','1140');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.card_clearing','1150');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.customer_advances','2110');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.card_fee','6710');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_unrealized_gain','7110');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.fx_unrealized_loss','7210');
INSERT INTO app_settings(setting_key,setting_value) VALUES ('map.retained_earnings','3200');

UPDATE payment_methods SET account_code='1150' WHERE code='CARD';
